### ISSUE TITLE
unable to set main character with seat-groups

### ISSUE THREAD

**Issue by odboEVEtech** [herpaderpaldent/seat-groups#107]
Hi, I just installed seat-groups, and I am unable to set my main character. Seat just reads no main character selected in the users section, and when I try to set a main character, the command sut stalls.. I have attached screenshots of both the seat groups page with the error regarding main character and the users screen. Any help would be appreciated. 

Thank you.

Screenshot of seat users page: https://imgur.com/a/0LiUvoq
Screenshot of seat groups page: https://imgur.com/a/Bq0kdxq

**Comment by herpaderpaldent** [comment]
Hey @odboEVEtech 

The error you see is based on the fact that your usergroup does not have a main_character defined. This is why seat-groups redirects you to your profile settings page. You see in the URL that it does not have anything to do with seat-groups but seat in its core.

To solve that: on `/profile/settings`:
1. Check the dropdown `MainCharacter` and check which of your characters should be considered as `main`
2. scroll further down on this page until you see `Update`
3. click on `update`

done.

If you have trouble with this guide, please reopen this issue.

**Comment by odboEVEtech** [comment]
Hi herp, 
I had one of my end users do this while I was watching the logs. The success message popped up, and it recorded the change in the security logs, but when I go to users under settings, it still shows no main character. 
the site is https://seat.crusader-eve.com
Would it be possible to coordinate a time where you and I can get together at the same time to look into this please?

**Comment by akturis** [comment]
I have the same issue
maybe problem in missed field "main_character_id" from table "groups"
im added field and issue is gone
